### ISSUE TITLE
Suggestion - add recommended dirs/files for PVE VE backup

### ISSUE THREAD

**Issue by yuriw** [Corsinvest/cv4pve-node-protect#1]
I think it'd be useful if in README you added an example(s) of what files and dirs are recommended for backup.

For example I used `--paths "/etc/."  --paths "/etc/pve/lxc/." --paths "/etc/pve/qemu-server/." --paths "/etc/pve/storage.cfg"` but not sure if this is a complete list.

@franklupo 
Thank you for this tool !

**Comment by franklupo** [comment]
Hi,
If you use "/etc/." you run the whole "/etc" folder.

```sh
/etc/. 
/var/lib/pve-cluster/.
/var/lib/ceph/.
```

**/root** is not a good selection.
If you know other folders please let me know.

Best rerards

**Comment by yuriw** [comment]
Well, if I used `--paths "/etc/."` I don't see content of `/etc/pve/lxc/` `/etc/pve/qemu-server/` `/etc/pve/storage.cfg`

See attached.

[test.tar.gz](https://github.com/Corsinvest/cv4pve-node-protect/files/5803767/test.tar.gz)

what am I missing ?

**Comment by franklupo** [comment]
Hi,
the '/etc/pve/lxc/' '/etc/pve/qemu-server/' are symbolic link.
![etc_pve](https://user-images.githubusercontent.com/6276309/104356128-dc107780-550b-11eb-8c5d-a9d79617618f.png)

The file are '/etc/pve/nodes/pve/
![etc_pve_nodes_pve](https://user-images.githubusercontent.com/6276309/104356129-dca90e00-550b-11eb-9d95-5ccd20ea5131.png)


Best regards

**Comment by yuriw** [comment]
On Ubuntu it does not look like you shown:

**Comment by yuriw** [comment]
@franklupo you are right, thx
