### ISSUE TITLE
password less option

### ISSUE THREAD

**Issue by yuriw** [Corsinvest/cv4pve-node-protect#2]
Thanks for this tool !

Assuming password less option enabled, it'd be good to allow `--password` be omitted or empty.

**Comment by franklupo** [comment]
Hi,
The password empty is not a good idea

Best regard

**Comment by yuriw** [comment]
@franklupo say if you enabled ssh key validation and when you ssh your host does not require to use a password.
And yet  cv4pve-node-protect will not run without password, which get exposed if you use email notifications fro crontab.
Why is it useful ?

**Comment by franklupo** [comment]
For example to call from windows.
